version: '3.0'

services:
  postgres:
    environment: &postgres_env
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    environment: &backend_env
      <<: *postgres_env
      RAILS_MASTER_KEY:
      RAILS_MAX_THREADS:
      RAILS_ENV: production
      POSTGRES_HOST: postgres
    build:
      args:
        REPOSITORY: git@github.com:dmlaziuk/todo.git
        BRANCH: master
    volumes:
      - ./log:/var/www/todo/log
      - ./tmp:/var/www/todo/tmp
      - public:/var/www/todo/public
    command: sh -c "./docker-entrypoint.sh"

  nginx:
    environment: &nginx_env
      TZ: Europe/Minsk
      LETSENCRYPT: 'false'
      LE_EMAIL: dm.laziuk@gmail.com
      LE_FQDN: krevoe.com
      SSL_CERT: le-crt.pem
      SSL_KEY: le-key.pem
      SSL_CHAIN_CERT: le-chain-crt.pem
    image: todo/nginx
    build:
      context: ./docker/nginx
      args:
        ENVIRONMENT: production
    hostname: nginx
    restart: always
    volumes:
        - ./ssl:/etc/nginx/ssl
        - ./tmp:/var/www/todo/tmp
        - ./log:/var/www/todo/log
        - public:/var/www/todo/public
    depends_on:
      - backend
    ports:
        - 80:80
        - 443:443

volumes:
  public:
